/* Automatically @generated by tree-sitter v0.25.4 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 28
#define LARGE_STATE_COUNT 24
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_ATimport = 2,
  anon_sym_ATconstrain = 3,
  anon_sym_ATcontext = 4,
  anon_sym_AToverride = 5,
  anon_sym_EQ = 6,
  anon_sym_DOT = 7,
  anon_sym_COMMA = 8,
  anon_sym_GT = 9,
  anon_sym_COLON = 10,
  anon_sym_PIPE = 11,
  anon_sym_STAR = 12,
  anon_sym_LPAREN = 13,
  anon_sym_RPAREN = 14,
  anon_sym_LBRACE = 15,
  anon_sym_RBRACE = 16,
  sym_line_comment = 17,
  sym_block_comment = 18,
  sym__double_quoted_string = 19,
  sym__single_quoted_string = 20,
  anon_sym_true = 21,
  anon_sym_false = 22,
  sym_number = 23,
  sym_identifier = 24,
  sym_source_file = 25,
  sym_statement = 26,
  sym_directive = 27,
  sym_assignment = 28,
  sym_expression = 29,
  sym_operator = 30,
  sym_parens = 31,
  sym_block = 32,
  sym_string = 33,
  sym_boolean = 34,
  aux_sym_source_file_repeat1 = 35,
  aux_sym_parens_repeat1 = 36,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_ATimport] = "@import",
  [anon_sym_ATconstrain] = "@constrain",
  [anon_sym_ATcontext] = "@context",
  [anon_sym_AToverride] = "@override",
  [anon_sym_EQ] = "=",
  [anon_sym_DOT] = ".",
  [anon_sym_COMMA] = ",",
  [anon_sym_GT] = ">",
  [anon_sym_COLON] = ":",
  [anon_sym_PIPE] = "|",
  [anon_sym_STAR] = "*",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym__double_quoted_string] = "_double_quoted_string",
  [sym__single_quoted_string] = "_single_quoted_string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_number] = "number",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym_statement] = "statement",
  [sym_directive] = "directive",
  [sym_assignment] = "assignment",
  [sym_expression] = "expression",
  [sym_operator] = "operator",
  [sym_parens] = "parens",
  [sym_block] = "block",
  [sym_string] = "string",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parens_repeat1] = "parens_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_ATimport] = anon_sym_ATimport,
  [anon_sym_ATconstrain] = anon_sym_ATconstrain,
  [anon_sym_ATcontext] = anon_sym_ATcontext,
  [anon_sym_AToverride] = anon_sym_AToverride,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym__double_quoted_string] = sym__double_quoted_string,
  [sym__single_quoted_string] = sym__single_quoted_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_number] = sym_number,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym_statement] = sym_statement,
  [sym_directive] = sym_directive,
  [sym_assignment] = sym_assignment,
  [sym_expression] = sym_expression,
  [sym_operator] = sym_operator,
  [sym_parens] = sym_parens,
  [sym_block] = sym_block,
  [sym_string] = sym_string,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parens_repeat1] = aux_sym_parens_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATimport] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATconstrain] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATcontext] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AToverride] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__double_quoted_string] = {
    .visible = false,
    .named = true,
  },
  [sym__single_quoted_string] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_parens] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parens_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_value = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 19,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(35);
      ADVANCE_MAP(
        '"', 1,
        '\'', 2,
        '(', 48,
        ')', 49,
        '*', 47,
        ',', 43,
        '.', 42,
        '/', 3,
        ':', 45,
        ';', 36,
        '=', 41,
        '>', 44,
        '@', 7,
        'f', 62,
        't', 66,
        '{', 50,
        '|', 46,
        '}', 51,
        '+', 31,
        '-', 31,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(54);
      if (lookahead == '\\') ADVANCE(33);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(55);
      if (lookahead == '\\') ADVANCE(34);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(52);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(53);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(17);
      if (lookahead == 'i') ADVANCE(14);
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 8:
      if (lookahead == 'd') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(8);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(16);
      END_STATE();
    case 14:
      if (lookahead == 'm') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 19:
      if (lookahead == 'p') ADVANCE(18);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(6);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(27);
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 28:
      if (lookahead == 'v') ADVANCE(9);
      END_STATE();
    case 29:
      if (lookahead == 'x') ADVANCE(26);
      END_STATE();
    case 30:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 33:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 34:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_ATimport);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_ATconstrain);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_ATcontext);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_AToverride);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__double_quoted_string);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__single_quoted_string);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(60);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_ATimport] = ACTIONS(1),
    [anon_sym_ATconstrain] = ACTIONS(1),
    [anon_sym_ATcontext] = ACTIONS(1),
    [anon_sym_AToverride] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym__double_quoted_string] = ACTIONS(1),
    [sym__single_quoted_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(27),
    [sym_statement] = STATE(4),
    [sym_directive] = STATE(19),
    [sym_assignment] = STATE(19),
    [sym_expression] = STATE(19),
    [sym_operator] = STATE(12),
    [sym_parens] = STATE(12),
    [sym_block] = STATE(12),
    [sym_string] = STATE(12),
    [sym_boolean] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_ATimport] = ACTIONS(7),
    [anon_sym_ATconstrain] = ACTIONS(9),
    [anon_sym_ATcontext] = ACTIONS(11),
    [anon_sym_AToverride] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(13),
    [anon_sym_COLON] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym__double_quoted_string] = ACTIONS(19),
    [sym__single_quoted_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_number] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
  },
  [STATE(2)] = {
    [sym_statement] = STATE(2),
    [sym_directive] = STATE(19),
    [sym_assignment] = STATE(19),
    [sym_expression] = STATE(19),
    [sym_operator] = STATE(12),
    [sym_parens] = STATE(12),
    [sym_block] = STATE(12),
    [sym_string] = STATE(12),
    [sym_boolean] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(27),
    [anon_sym_ATimport] = ACTIONS(29),
    [anon_sym_ATconstrain] = ACTIONS(32),
    [anon_sym_ATcontext] = ACTIONS(35),
    [anon_sym_AToverride] = ACTIONS(32),
    [anon_sym_DOT] = ACTIONS(38),
    [anon_sym_COMMA] = ACTIONS(38),
    [anon_sym_GT] = ACTIONS(38),
    [anon_sym_COLON] = ACTIONS(38),
    [anon_sym_PIPE] = ACTIONS(38),
    [anon_sym_STAR] = ACTIONS(38),
    [anon_sym_LPAREN] = ACTIONS(41),
    [anon_sym_LBRACE] = ACTIONS(44),
    [anon_sym_RBRACE] = ACTIONS(27),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym__double_quoted_string] = ACTIONS(47),
    [sym__single_quoted_string] = ACTIONS(47),
    [anon_sym_true] = ACTIONS(50),
    [anon_sym_false] = ACTIONS(50),
    [sym_number] = ACTIONS(53),
    [sym_identifier] = ACTIONS(56),
  },
  [STATE(3)] = {
    [sym_statement] = STATE(5),
    [sym_directive] = STATE(19),
    [sym_assignment] = STATE(19),
    [sym_expression] = STATE(19),
    [sym_operator] = STATE(12),
    [sym_parens] = STATE(12),
    [sym_block] = STATE(12),
    [sym_string] = STATE(12),
    [sym_boolean] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(5),
    [anon_sym_ATimport] = ACTIONS(7),
    [anon_sym_ATconstrain] = ACTIONS(9),
    [anon_sym_ATcontext] = ACTIONS(11),
    [anon_sym_AToverride] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(13),
    [anon_sym_COLON] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(59),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym__double_quoted_string] = ACTIONS(19),
    [sym__single_quoted_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_number] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
  },
  [STATE(4)] = {
    [sym_statement] = STATE(2),
    [sym_directive] = STATE(19),
    [sym_assignment] = STATE(19),
    [sym_expression] = STATE(19),
    [sym_operator] = STATE(12),
    [sym_parens] = STATE(12),
    [sym_block] = STATE(12),
    [sym_string] = STATE(12),
    [sym_boolean] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(61),
    [anon_sym_ATimport] = ACTIONS(7),
    [anon_sym_ATconstrain] = ACTIONS(9),
    [anon_sym_ATcontext] = ACTIONS(11),
    [anon_sym_AToverride] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(13),
    [anon_sym_COLON] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym__double_quoted_string] = ACTIONS(19),
    [sym__single_quoted_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_number] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
  },
  [STATE(5)] = {
    [sym_statement] = STATE(2),
    [sym_directive] = STATE(19),
    [sym_assignment] = STATE(19),
    [sym_expression] = STATE(19),
    [sym_operator] = STATE(12),
    [sym_parens] = STATE(12),
    [sym_block] = STATE(12),
    [sym_string] = STATE(12),
    [sym_boolean] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_ATimport] = ACTIONS(7),
    [anon_sym_ATconstrain] = ACTIONS(9),
    [anon_sym_ATcontext] = ACTIONS(11),
    [anon_sym_AToverride] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(13),
    [anon_sym_COLON] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(63),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym__double_quoted_string] = ACTIONS(19),
    [sym__single_quoted_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_number] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
  },
  [STATE(6)] = {
    [sym_statement] = STATE(22),
    [sym_directive] = STATE(23),
    [sym_assignment] = STATE(23),
    [sym_expression] = STATE(23),
    [sym_operator] = STATE(12),
    [sym_parens] = STATE(12),
    [sym_block] = STATE(12),
    [sym_string] = STATE(12),
    [sym_boolean] = STATE(12),
    [anon_sym_ATimport] = ACTIONS(7),
    [anon_sym_ATconstrain] = ACTIONS(9),
    [anon_sym_ATcontext] = ACTIONS(11),
    [anon_sym_AToverride] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(13),
    [anon_sym_COLON] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym__double_quoted_string] = ACTIONS(19),
    [sym__single_quoted_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_number] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(65),
    [anon_sym_SEMI] = ACTIONS(65),
    [anon_sym_ATimport] = ACTIONS(65),
    [anon_sym_ATconstrain] = ACTIONS(65),
    [anon_sym_ATcontext] = ACTIONS(65),
    [anon_sym_AToverride] = ACTIONS(65),
    [anon_sym_DOT] = ACTIONS(65),
    [anon_sym_COMMA] = ACTIONS(65),
    [anon_sym_GT] = ACTIONS(65),
    [anon_sym_COLON] = ACTIONS(65),
    [anon_sym_PIPE] = ACTIONS(65),
    [anon_sym_STAR] = ACTIONS(65),
    [anon_sym_LPAREN] = ACTIONS(65),
    [anon_sym_RPAREN] = ACTIONS(65),
    [anon_sym_LBRACE] = ACTIONS(65),
    [anon_sym_RBRACE] = ACTIONS(65),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym__double_quoted_string] = ACTIONS(65),
    [sym__single_quoted_string] = ACTIONS(65),
    [anon_sym_true] = ACTIONS(67),
    [anon_sym_false] = ACTIONS(67),
    [sym_number] = ACTIONS(65),
    [sym_identifier] = ACTIONS(67),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(69),
    [anon_sym_SEMI] = ACTIONS(69),
    [anon_sym_ATimport] = ACTIONS(69),
    [anon_sym_ATconstrain] = ACTIONS(69),
    [anon_sym_ATcontext] = ACTIONS(69),
    [anon_sym_AToverride] = ACTIONS(69),
    [anon_sym_DOT] = ACTIONS(69),
    [anon_sym_COMMA] = ACTIONS(69),
    [anon_sym_GT] = ACTIONS(69),
    [anon_sym_COLON] = ACTIONS(69),
    [anon_sym_PIPE] = ACTIONS(69),
    [anon_sym_STAR] = ACTIONS(69),
    [anon_sym_LPAREN] = ACTIONS(69),
    [anon_sym_RPAREN] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(69),
    [anon_sym_RBRACE] = ACTIONS(69),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym__double_quoted_string] = ACTIONS(69),
    [sym__single_quoted_string] = ACTIONS(69),
    [anon_sym_true] = ACTIONS(71),
    [anon_sym_false] = ACTIONS(71),
    [sym_number] = ACTIONS(69),
    [sym_identifier] = ACTIONS(71),
  },
  [STATE(9)] = {
    [sym_expression] = STATE(13),
    [sym_operator] = STATE(12),
    [sym_parens] = STATE(12),
    [sym_block] = STATE(12),
    [sym_string] = STATE(12),
    [sym_boolean] = STATE(12),
    [aux_sym_parens_repeat1] = STATE(13),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(13),
    [anon_sym_COLON] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(73),
    [anon_sym_LBRACE] = ACTIONS(17),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym__double_quoted_string] = ACTIONS(19),
    [sym__single_quoted_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_number] = ACTIONS(23),
    [sym_identifier] = ACTIONS(75),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(77),
    [anon_sym_SEMI] = ACTIONS(77),
    [anon_sym_ATimport] = ACTIONS(77),
    [anon_sym_ATconstrain] = ACTIONS(77),
    [anon_sym_ATcontext] = ACTIONS(77),
    [anon_sym_AToverride] = ACTIONS(77),
    [anon_sym_EQ] = ACTIONS(79),
    [anon_sym_DOT] = ACTIONS(77),
    [anon_sym_COMMA] = ACTIONS(77),
    [anon_sym_GT] = ACTIONS(77),
    [anon_sym_COLON] = ACTIONS(77),
    [anon_sym_PIPE] = ACTIONS(77),
    [anon_sym_STAR] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(77),
    [anon_sym_LBRACE] = ACTIONS(77),
    [anon_sym_RBRACE] = ACTIONS(77),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym__double_quoted_string] = ACTIONS(77),
    [sym__single_quoted_string] = ACTIONS(77),
    [anon_sym_true] = ACTIONS(81),
    [anon_sym_false] = ACTIONS(81),
    [sym_number] = ACTIONS(77),
    [sym_identifier] = ACTIONS(81),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(83),
    [anon_sym_SEMI] = ACTIONS(83),
    [anon_sym_ATimport] = ACTIONS(83),
    [anon_sym_ATconstrain] = ACTIONS(83),
    [anon_sym_ATcontext] = ACTIONS(83),
    [anon_sym_AToverride] = ACTIONS(83),
    [anon_sym_DOT] = ACTIONS(83),
    [anon_sym_COMMA] = ACTIONS(83),
    [anon_sym_GT] = ACTIONS(83),
    [anon_sym_COLON] = ACTIONS(83),
    [anon_sym_PIPE] = ACTIONS(83),
    [anon_sym_STAR] = ACTIONS(83),
    [anon_sym_LPAREN] = ACTIONS(83),
    [anon_sym_RPAREN] = ACTIONS(83),
    [anon_sym_LBRACE] = ACTIONS(83),
    [anon_sym_RBRACE] = ACTIONS(83),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym__double_quoted_string] = ACTIONS(83),
    [sym__single_quoted_string] = ACTIONS(83),
    [anon_sym_true] = ACTIONS(85),
    [anon_sym_false] = ACTIONS(85),
    [sym_number] = ACTIONS(83),
    [sym_identifier] = ACTIONS(85),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(77),
    [anon_sym_SEMI] = ACTIONS(77),
    [anon_sym_ATimport] = ACTIONS(77),
    [anon_sym_ATconstrain] = ACTIONS(77),
    [anon_sym_ATcontext] = ACTIONS(77),
    [anon_sym_AToverride] = ACTIONS(77),
    [anon_sym_DOT] = ACTIONS(77),
    [anon_sym_COMMA] = ACTIONS(77),
    [anon_sym_GT] = ACTIONS(77),
    [anon_sym_COLON] = ACTIONS(77),
    [anon_sym_PIPE] = ACTIONS(77),
    [anon_sym_STAR] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(77),
    [anon_sym_RPAREN] = ACTIONS(77),
    [anon_sym_LBRACE] = ACTIONS(77),
    [anon_sym_RBRACE] = ACTIONS(77),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym__double_quoted_string] = ACTIONS(77),
    [sym__single_quoted_string] = ACTIONS(77),
    [anon_sym_true] = ACTIONS(81),
    [anon_sym_false] = ACTIONS(81),
    [sym_number] = ACTIONS(77),
    [sym_identifier] = ACTIONS(81),
  },
  [STATE(13)] = {
    [sym_expression] = STATE(16),
    [sym_operator] = STATE(12),
    [sym_parens] = STATE(12),
    [sym_block] = STATE(12),
    [sym_string] = STATE(12),
    [sym_boolean] = STATE(12),
    [aux_sym_parens_repeat1] = STATE(16),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(13),
    [anon_sym_COLON] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(87),
    [anon_sym_LBRACE] = ACTIONS(17),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym__double_quoted_string] = ACTIONS(19),
    [sym__single_quoted_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_number] = ACTIONS(23),
    [sym_identifier] = ACTIONS(75),
  },
  [STATE(14)] = {
    [ts_builtin_sym_end] = ACTIONS(89),
    [anon_sym_SEMI] = ACTIONS(89),
    [anon_sym_ATimport] = ACTIONS(89),
    [anon_sym_ATconstrain] = ACTIONS(89),
    [anon_sym_ATcontext] = ACTIONS(89),
    [anon_sym_AToverride] = ACTIONS(89),
    [anon_sym_DOT] = ACTIONS(89),
    [anon_sym_COMMA] = ACTIONS(89),
    [anon_sym_GT] = ACTIONS(89),
    [anon_sym_COLON] = ACTIONS(89),
    [anon_sym_PIPE] = ACTIONS(89),
    [anon_sym_STAR] = ACTIONS(89),
    [anon_sym_LPAREN] = ACTIONS(89),
    [anon_sym_RPAREN] = ACTIONS(89),
    [anon_sym_LBRACE] = ACTIONS(89),
    [anon_sym_RBRACE] = ACTIONS(89),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym__double_quoted_string] = ACTIONS(89),
    [sym__single_quoted_string] = ACTIONS(89),
    [anon_sym_true] = ACTIONS(91),
    [anon_sym_false] = ACTIONS(91),
    [sym_number] = ACTIONS(89),
    [sym_identifier] = ACTIONS(91),
  },
  [STATE(15)] = {
    [ts_builtin_sym_end] = ACTIONS(93),
    [anon_sym_SEMI] = ACTIONS(93),
    [anon_sym_ATimport] = ACTIONS(93),
    [anon_sym_ATconstrain] = ACTIONS(93),
    [anon_sym_ATcontext] = ACTIONS(93),
    [anon_sym_AToverride] = ACTIONS(93),
    [anon_sym_DOT] = ACTIONS(93),
    [anon_sym_COMMA] = ACTIONS(93),
    [anon_sym_GT] = ACTIONS(93),
    [anon_sym_COLON] = ACTIONS(93),
    [anon_sym_PIPE] = ACTIONS(93),
    [anon_sym_STAR] = ACTIONS(93),
    [anon_sym_LPAREN] = ACTIONS(93),
    [anon_sym_RPAREN] = ACTIONS(93),
    [anon_sym_LBRACE] = ACTIONS(93),
    [anon_sym_RBRACE] = ACTIONS(93),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym__double_quoted_string] = ACTIONS(93),
    [sym__single_quoted_string] = ACTIONS(93),
    [anon_sym_true] = ACTIONS(95),
    [anon_sym_false] = ACTIONS(95),
    [sym_number] = ACTIONS(93),
    [sym_identifier] = ACTIONS(95),
  },
  [STATE(16)] = {
    [sym_expression] = STATE(16),
    [sym_operator] = STATE(12),
    [sym_parens] = STATE(12),
    [sym_block] = STATE(12),
    [sym_string] = STATE(12),
    [sym_boolean] = STATE(12),
    [aux_sym_parens_repeat1] = STATE(16),
    [anon_sym_DOT] = ACTIONS(97),
    [anon_sym_COMMA] = ACTIONS(97),
    [anon_sym_GT] = ACTIONS(97),
    [anon_sym_COLON] = ACTIONS(97),
    [anon_sym_PIPE] = ACTIONS(97),
    [anon_sym_STAR] = ACTIONS(97),
    [anon_sym_LPAREN] = ACTIONS(100),
    [anon_sym_RPAREN] = ACTIONS(103),
    [anon_sym_LBRACE] = ACTIONS(105),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym__double_quoted_string] = ACTIONS(108),
    [sym__single_quoted_string] = ACTIONS(108),
    [anon_sym_true] = ACTIONS(111),
    [anon_sym_false] = ACTIONS(111),
    [sym_number] = ACTIONS(114),
    [sym_identifier] = ACTIONS(117),
  },
  [STATE(17)] = {
    [ts_builtin_sym_end] = ACTIONS(120),
    [anon_sym_SEMI] = ACTIONS(120),
    [anon_sym_ATimport] = ACTIONS(120),
    [anon_sym_ATconstrain] = ACTIONS(120),
    [anon_sym_ATcontext] = ACTIONS(120),
    [anon_sym_AToverride] = ACTIONS(120),
    [anon_sym_DOT] = ACTIONS(120),
    [anon_sym_COMMA] = ACTIONS(120),
    [anon_sym_GT] = ACTIONS(120),
    [anon_sym_COLON] = ACTIONS(120),
    [anon_sym_PIPE] = ACTIONS(120),
    [anon_sym_STAR] = ACTIONS(120),
    [anon_sym_LPAREN] = ACTIONS(120),
    [anon_sym_RPAREN] = ACTIONS(120),
    [anon_sym_LBRACE] = ACTIONS(120),
    [anon_sym_RBRACE] = ACTIONS(120),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym__double_quoted_string] = ACTIONS(120),
    [sym__single_quoted_string] = ACTIONS(120),
    [anon_sym_true] = ACTIONS(122),
    [anon_sym_false] = ACTIONS(122),
    [sym_number] = ACTIONS(120),
    [sym_identifier] = ACTIONS(122),
  },
  [STATE(18)] = {
    [ts_builtin_sym_end] = ACTIONS(124),
    [anon_sym_SEMI] = ACTIONS(124),
    [anon_sym_ATimport] = ACTIONS(124),
    [anon_sym_ATconstrain] = ACTIONS(124),
    [anon_sym_ATcontext] = ACTIONS(124),
    [anon_sym_AToverride] = ACTIONS(124),
    [anon_sym_DOT] = ACTIONS(124),
    [anon_sym_COMMA] = ACTIONS(124),
    [anon_sym_GT] = ACTIONS(124),
    [anon_sym_COLON] = ACTIONS(124),
    [anon_sym_PIPE] = ACTIONS(124),
    [anon_sym_STAR] = ACTIONS(124),
    [anon_sym_LPAREN] = ACTIONS(124),
    [anon_sym_RPAREN] = ACTIONS(124),
    [anon_sym_LBRACE] = ACTIONS(124),
    [anon_sym_RBRACE] = ACTIONS(124),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym__double_quoted_string] = ACTIONS(124),
    [sym__single_quoted_string] = ACTIONS(124),
    [anon_sym_true] = ACTIONS(126),
    [anon_sym_false] = ACTIONS(126),
    [sym_number] = ACTIONS(124),
    [sym_identifier] = ACTIONS(126),
  },
  [STATE(19)] = {
    [ts_builtin_sym_end] = ACTIONS(128),
    [anon_sym_SEMI] = ACTIONS(130),
    [anon_sym_ATimport] = ACTIONS(128),
    [anon_sym_ATconstrain] = ACTIONS(128),
    [anon_sym_ATcontext] = ACTIONS(128),
    [anon_sym_AToverride] = ACTIONS(128),
    [anon_sym_DOT] = ACTIONS(128),
    [anon_sym_COMMA] = ACTIONS(128),
    [anon_sym_GT] = ACTIONS(128),
    [anon_sym_COLON] = ACTIONS(128),
    [anon_sym_PIPE] = ACTIONS(128),
    [anon_sym_STAR] = ACTIONS(128),
    [anon_sym_LPAREN] = ACTIONS(128),
    [anon_sym_LBRACE] = ACTIONS(128),
    [anon_sym_RBRACE] = ACTIONS(128),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym__double_quoted_string] = ACTIONS(128),
    [sym__single_quoted_string] = ACTIONS(128),
    [anon_sym_true] = ACTIONS(132),
    [anon_sym_false] = ACTIONS(132),
    [sym_number] = ACTIONS(128),
    [sym_identifier] = ACTIONS(132),
  },
  [STATE(20)] = {
    [ts_builtin_sym_end] = ACTIONS(134),
    [anon_sym_SEMI] = ACTIONS(134),
    [anon_sym_ATimport] = ACTIONS(134),
    [anon_sym_ATconstrain] = ACTIONS(134),
    [anon_sym_ATcontext] = ACTIONS(134),
    [anon_sym_AToverride] = ACTIONS(134),
    [anon_sym_DOT] = ACTIONS(134),
    [anon_sym_COMMA] = ACTIONS(134),
    [anon_sym_GT] = ACTIONS(134),
    [anon_sym_COLON] = ACTIONS(134),
    [anon_sym_PIPE] = ACTIONS(134),
    [anon_sym_STAR] = ACTIONS(134),
    [anon_sym_LPAREN] = ACTIONS(134),
    [anon_sym_LBRACE] = ACTIONS(134),
    [anon_sym_RBRACE] = ACTIONS(134),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym__double_quoted_string] = ACTIONS(134),
    [sym__single_quoted_string] = ACTIONS(134),
    [anon_sym_true] = ACTIONS(136),
    [anon_sym_false] = ACTIONS(136),
    [sym_number] = ACTIONS(134),
    [sym_identifier] = ACTIONS(136),
  },
  [STATE(21)] = {
    [ts_builtin_sym_end] = ACTIONS(138),
    [anon_sym_SEMI] = ACTIONS(138),
    [anon_sym_ATimport] = ACTIONS(138),
    [anon_sym_ATconstrain] = ACTIONS(138),
    [anon_sym_ATcontext] = ACTIONS(138),
    [anon_sym_AToverride] = ACTIONS(138),
    [anon_sym_DOT] = ACTIONS(138),
    [anon_sym_COMMA] = ACTIONS(138),
    [anon_sym_GT] = ACTIONS(138),
    [anon_sym_COLON] = ACTIONS(138),
    [anon_sym_PIPE] = ACTIONS(138),
    [anon_sym_STAR] = ACTIONS(138),
    [anon_sym_LPAREN] = ACTIONS(138),
    [anon_sym_LBRACE] = ACTIONS(138),
    [anon_sym_RBRACE] = ACTIONS(138),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym__double_quoted_string] = ACTIONS(138),
    [sym__single_quoted_string] = ACTIONS(138),
    [anon_sym_true] = ACTIONS(140),
    [anon_sym_false] = ACTIONS(140),
    [sym_number] = ACTIONS(138),
    [sym_identifier] = ACTIONS(140),
  },
  [STATE(22)] = {
    [ts_builtin_sym_end] = ACTIONS(142),
    [anon_sym_SEMI] = ACTIONS(142),
    [anon_sym_ATimport] = ACTIONS(142),
    [anon_sym_ATconstrain] = ACTIONS(142),
    [anon_sym_ATcontext] = ACTIONS(142),
    [anon_sym_AToverride] = ACTIONS(142),
    [anon_sym_DOT] = ACTIONS(142),
    [anon_sym_COMMA] = ACTIONS(142),
    [anon_sym_GT] = ACTIONS(142),
    [anon_sym_COLON] = ACTIONS(142),
    [anon_sym_PIPE] = ACTIONS(142),
    [anon_sym_STAR] = ACTIONS(142),
    [anon_sym_LPAREN] = ACTIONS(142),
    [anon_sym_LBRACE] = ACTIONS(142),
    [anon_sym_RBRACE] = ACTIONS(142),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym__double_quoted_string] = ACTIONS(142),
    [sym__single_quoted_string] = ACTIONS(142),
    [anon_sym_true] = ACTIONS(144),
    [anon_sym_false] = ACTIONS(144),
    [sym_number] = ACTIONS(142),
    [sym_identifier] = ACTIONS(144),
  },
  [STATE(23)] = {
    [ts_builtin_sym_end] = ACTIONS(128),
    [anon_sym_SEMI] = ACTIONS(128),
    [anon_sym_ATimport] = ACTIONS(128),
    [anon_sym_ATconstrain] = ACTIONS(128),
    [anon_sym_ATcontext] = ACTIONS(128),
    [anon_sym_AToverride] = ACTIONS(128),
    [anon_sym_DOT] = ACTIONS(128),
    [anon_sym_COMMA] = ACTIONS(128),
    [anon_sym_GT] = ACTIONS(128),
    [anon_sym_COLON] = ACTIONS(128),
    [anon_sym_PIPE] = ACTIONS(128),
    [anon_sym_STAR] = ACTIONS(128),
    [anon_sym_LPAREN] = ACTIONS(128),
    [anon_sym_LBRACE] = ACTIONS(128),
    [anon_sym_RBRACE] = ACTIONS(128),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym__double_quoted_string] = ACTIONS(128),
    [sym__single_quoted_string] = ACTIONS(128),
    [anon_sym_true] = ACTIONS(132),
    [anon_sym_false] = ACTIONS(132),
    [sym_number] = ACTIONS(128),
    [sym_identifier] = ACTIONS(132),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(146), 1,
      sym_number,
    ACTIONS(148), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(19), 2,
      sym__double_quoted_string,
      sym__single_quoted_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 2,
      sym_string,
      sym_boolean,
  [23] = 3,
    STATE(22), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(19), 2,
      sym__double_quoted_string,
      sym__single_quoted_string,
  [35] = 3,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    STATE(22), 1,
      sym_parens,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [46] = 2,
    ACTIONS(150), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(24)] = 0,
  [SMALL_STATE(25)] = 23,
  [SMALL_STATE(26)] = 35,
  [SMALL_STATE(27)] = 46,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parens, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parens, 2, 0, 0),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parens_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parens_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parens_repeat1, 2, 0, 0),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parens_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [108] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parens_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [111] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_parens_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parens_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [117] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_parens_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parens, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parens, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 1),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 1),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [150] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ccs(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ccs",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
